language: python
python:
  - "3.6"

# Install dependencies
install:
  - pip install -r requirements.txt -q

# Run the tests
script:
  - nosetests --wtih-coverage

# Code coverage
after_success:
  - coveralls
